### ISSUE TITLE
Review Archipelago

### ISSUE THREAD

**Issue by gheber** [SEEKCommons/resource-hub#33]
@unixjazz brought this up: https://archipelago.nyc/

> Archipelago is a slim, smart, open source repository software.

- Is that what we need? (rather than working w/ existing repos...)
- Docs. [here](https://github.com/esmero/archipelago-documentation). High quality!
- Lotsa JSON 🤔

**Comment by unixjazz** [comment]
We are settling with Gala for now, so closing this.
