### ISSUE TITLE
Present the resource hub ideas to the team

### ISSUE THREAD

**Issue by gheber** [SEEKCommons/resource-hub#7]
- What other options are out there?
- It's not an either/or
- DFC is building on top of RH
- Not everyone (most others) won't use RH directly
- Where and how does data curation occur? Standards?
  - A format that can be ingested into WD?
  - Fellows and networkers need guidance! => example notebooks
- Schedule the meeting after the DFC/RH meeting-of-the-minds

**Comment by unixjazz** [comment]
This has been completed with the onboarding of Gala (for the interface DFC<-->RH, closing it here as deprecated.
